{
 "PRed": [
  {
   "PR": {
    "__lazy_json__": "pr_json/1586983883.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "boost_cpp_to_libboost"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.11.02.10.11.59",
 "pre_pr_migrator_attempts": {
  "boost1780": 10,
  "pypy38": 3,
  "python310": 415,
  "python311": 793,
  "python312": 38
 },
 "pre_pr_migrator_status": {
  "boost1780": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3335241253\">bot CI job</a>): main: ['linux_64_python3.10.____cpythonrdkit_version2020.09._: Encountered problems while solving:\\n  - package rdkit-2020.09.1-py36hce6e9d5_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed\\n', 'linux_64_python3.10.____cpythonrdkit_version2021.03._: Encountered problems while solving:\\n  - package rdkit-2021.03.1-py36h59cdaa9_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed\\n', 'linux_64_python3.10.____cpythonrdkit_version2021.09._: Encountered problems while solving:\\n  - package rdkit-2021.09.1-py37h13c2175_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2020.09._: Encountered problems while solving:\\n  - package rdkit-2020.09.1-py36he4cb02f_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2021.03._: Encountered problems while solving:\\n  - package rdkit-2021.03.1-py36h7ddc302_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2021.09._: Encountered problems while solving:\\n  - package rdkit-2021.09.1-py37h9710f2f_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n']",
  "pypy38": "bot error (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3940553421\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1166, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 279, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 340, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n",
  "python310": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/2918752635\">bot CI job</a>): main: ['linux_64_python3.10.____cpythonrdkit_version2020.09._: Encountered problems while solving:\\n  - package rdkit-2020.09.1-py39h931a474_0 requires boost >=1.72.0,<1.72.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.10.____cpythonrdkit_version2021.03._: Encountered problems while solving:\\n  - package rdkit-2021.03.5-py36hbacbb34_0 requires boost >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.10.____cpythonrdkit_version2021.09._: Encountered problems while solving:\\n  - package rdkit-2021.09.1-py37h13c2175_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2020.09._: Encountered problems while solving:\\n  - package rdkit-2020.09.1-py39ha612541_0 requires boost >=1.72.0,<1.72.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2021.03._: Encountered problems while solving:\\n  - package rdkit-2021.03.1-py36h7ddc302_0 requires boost >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpythonrdkit_version2021.09._: Encountered problems while solving:\\n  - package rdkit-2021.09.1-py37h9710f2f_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n']",
  "python311": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6288910810\">bot CI job</a>): main: ['linux_64_python3.11.____cpythonrdkit_version2022.03._: Encountered problems while solving:\\n  - package rdkit-2022.03.1-py37hc52db9c_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n', 'osx_64_python3.11.____cpythonrdkit_version2022.03._: Encountered problems while solving:\\n  - package rdkit-2022.03.1-py37h1462858_0 requires python_abi 3.7.* *_cp37m, but none of the providers can be installed\\n']",
  "python312": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/6841077632'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_python3.11.____cpythonrdkit_version2022.03._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.11.* *_cpython is installable and it requires\n\u2502  \u2514\u2500 python_abi 3.11.* *_cp311, which can be installed;\n\u2514\u2500 rdkit 2022.03.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n      \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported.</pre><pre>linux_64_python3.12.____cpythonrdkit_version2022.03._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.12.* *_cpython is installable with the potential options\n\u2502  \u251C\u2500 python 3.12.0 would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2502  \u2514\u2500 python 3.12.0rc3 would require\n\u2502     \u2514\u2500 _python_rc, which does not exist (perhaps a missing channel);\n\u2514\u2500 rdkit 2022.03.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n      \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported.</pre><pre>linux_64_python3.12.____cpythonrdkit_version2022.09._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.12.* *_cpython is installable with the potential options\n\u2502  \u251C\u2500 python 3.12.0 would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2502  \u2514\u2500 python 3.12.0rc3 would require\n\u2502     \u2514\u2500 _python_rc, which does not exist (perhaps a missing channel);\n\u2514\u2500 rdkit 2022.09.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit 2022.09.1 would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4] would require\n   \u2502  \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n      \u2514\u2500 python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported.</pre><pre>osx_64_python3.11.____cpythonrdkit_version2022.03._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.11.* *_cpython is installable and it requires\n\u2502  \u2514\u2500 python_abi 3.11.* *_cp311, which can be installed;\n\u2514\u2500 rdkit 2022.03.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n      \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported.</pre><pre>osx_64_python3.12.____cpythonrdkit_version2022.03._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.12.* *_cpython is installable with the potential options\n\u2502  \u251C\u2500 python 3.12.0 would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2502  \u2514\u2500 python 3.12.0rc3 would require\n\u2502     \u2514\u2500 _python_rc, which does not exist (perhaps a missing channel);\n\u2514\u2500 rdkit 2022.03.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.03.1|2022.03.2|2022.03.3|2022.03.4|2022.03.5] would require\n      \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported.</pre><pre>osx_64_python3.12.____cpythonrdkit_version2022.09._: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.12.* *_cpython is installable with the potential options\n\u2502  \u251C\u2500 python 3.12.0 would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.12.* *_cp312, which can be installed;\n\u2502  \u2514\u2500 python 3.12.0rc3 would require\n\u2502     \u2514\u2500 _python_rc, which does not exist (perhaps a missing channel);\n\u2514\u2500 rdkit 2022.09.*  is not installable because there are no viable options\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n   \u2502  \u2514\u2500 python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit 2022.09.1 would require\n   \u2502  \u2514\u2500 python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n   \u2502  \u2514\u2500 python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;\n   \u251C\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n   \u2502  \u2514\u2500 python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;\n   \u2514\u2500 rdkit [2022.09.1|2022.09.3|2022.09.4|2022.09.5] would require\n      \u2514\u2500 python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>"
 },
 "smithy_version": "3.27.1"
}